version: "3.8"

services:
  monorepo_dev:
    environment:
      - REDIS_URL=redis://redis_dev:6379
      - NODE_ENV=development
      - DATABASE_URL

    container_name: nestjs-remix-monorepo-dev
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000

  redis_dev:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server"]
    volumes:
      - ./cache:/data
